Repository ultralytics/JSON2YOLO, pull requests merged in 2025-01, with the labels that each got.

#113 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#114 Standardize license headers in Python files
  general_json2yolo.py
  labelbox_json2yolo.py
  utils.py
Labels: documentation

#115 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
Labels: devops, documentation
